on:
  pull_request:
    branches: main
    types: [closed]
  workflow_dispatch:
  
jobs:
  setup:
    runs-on: ubuntu-latest

    outputs:
      is_maintenance: ${{ steps.is_maintenance.outputs.result }}
      is_merged: ${{ steps.is_merged.outputs.result }}

    steps:
      - name: Check if maintenance
        id: is_maintenance
        run: |
          if [[ "${{ github.head_ref }}" =~ ^(fix/|change/) ]]; then
            echo "result=false" >> "$GITHUB_OUTPUT"
          else
            echo "result=true" >> "$GITHUB_OUTPUT"
          fi
      - name: Check if merged
        id: is_merged
        run: |
          if [[ "${{ github.event.pull_request.merged }}" == "true" ]]; then
            echo "result=true" >> "$GITHUB_OUTPUT"
          else
            echo "result=false" >> "$GITHUB_OUTPUT"
          fi

      - name: Summary
        run: |
          echo "IsMerged: ${{ steps.is_merged.outputs.result }} | IsMaintenance: ${{ steps.is_maintenance.outputs.result  }}"

  update:
    runs-on: ubuntu-latest
    needs: setup
    if: ${{ needs.setup.outputs.is_maintenance == 'false' && needs.setup.outputs.is_merged == 'true' }}
    
    permissions:
      contents: write
      pull-requests: write
      
    steps:
      - name: Update Task
        run: echo "UPDATE" >> $GITHUB_STEP_SUMMARY
      
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.ref }}
          repository: ${{ github.event.pull_request.head.repo.full_name }}

      - name: Version
        working-directory: ${{ github.workspace }}
        id: version
        run: |
          npm install commander > /dev/null
          echo "VERSION=$(node ./.github/versionUpdate.js -f app.config.js --field version)" >> "$GITHUB_OUTPUT"
          node ./.github/versionUpdate.js -f app.config.js --field version
        continue-on-error: false
      
      - name: Commit new version
        uses: EndBug/add-and-commit@v9
        with:
          default_author: github_actions
          message: "Updated minor version: ${{ steps.version_update.outputs.VERSION_SUMMARY }}"
          add: app.config.js
        continue-on-error: false
        
      - name: get version
        env:
          VERSION: ${{ steps.version.outputs.VERSION }}
        run: echo "App version update $VERSION"

  maintenance:
    runs-on: ubuntu-latest
    needs: setup
    if: ${{ needs.setup.outputs.is_maintenance == 'true' && needs.setup.outputs.is_merged == 'true' }}

    steps:
      - name: Maintenance Task
        run: |
          run: echo "MAINTENANCE" >> $GITHUB_STEP_SUMMARY

  closed_pr:
    runs-on: ubuntu-latest
    needs: setup
    if: ${{ needs.setup.outputs.is_merged == 'false' }}

    steps:
      - name: Maintenance Task
        run: echo "CLOSE PULL REQUEST" >> $GITHUB_STEP_SUMMARY
