name: test
on:
  workflow_dispatch

jobs:
  update:
    name: TEST
    runs-on: ubuntu-latest

    permissions:
      contents: read
      pull-requests: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.ref }}
          repository: ${{ github.event.pull_request.head.repo.full_name }}

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18.x

      - name: Get version
        working-directory: ${{ github.workspace }}
        run: |
          echo "{node ./getVersionScript.js app.config.js version}={test_var}" >> "$GITHUB_ENV"
          echo "### Hello world! :rocket:" >> $GITHUB_STEP_SUMMARY

      - name: next step
        run: echo "test var is $test_var"
