name: test
on:
  workflow_dispatch

jobs:
  update:
    name: TEST
    runs-on: ubuntu-latest

    permissions:
      contents: read
      pull-requests: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.ref }}
          repository: ${{ github.event.pull_request.head.repo.full_name }}

      - name: Get version
        working-directory: ${{ github.workspace }}
        id: version
        run: echo "TEST_VAR=$(node ./getVersionScript.js app.config.js version)" >> "$GITHUB_ENV"

      - name: Version summary
        env: 
          VERSION: ${{ steps.version.output.TEST_VAR }}
        run: |
          echo "test var is $VERSION"
          echo "### Hello world! :rocket: $VERSION" >> $GITHUB_STEP_SUMMARY
